// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlfi1XYyKPNQv4ohnVtQ2cl1BbQMCvAgI',
    appId: '1:265952109580:web:698aaae57184049773fa29',
    messagingSenderId: '265952109580',
    projectId: 'riverpod-course',
    authDomain: 'riverpod-course.firebaseapp.com',
    storageBucket: 'riverpod-course.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjVxwlm7A8GVGIiUASejVEDl7XgjnYNiw',
    appId: '1:265952109580:android:00ecb5f51caed21973fa29',
    messagingSenderId: '265952109580',
    projectId: 'riverpod-course',
    storageBucket: 'riverpod-course.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnUBfJY80ZS5YVkua4KE6AgesfvZDjVg4',
    appId: '1:265952109580:ios:8db591ce2d6a643573fa29',
    messagingSenderId: '265952109580',
    projectId: 'riverpod-course',
    storageBucket: 'riverpod-course.appspot.com',
    iosClientId: '265952109580-d8jjrt67pafc8p6g7e3nck6b8k41q0dg.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
